# Generated by Django 5.0.1 on 2024-01-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
